services:
  adonis-app:
    image: adonis_app
    container_name: adonis_app
    restart: unless-stopped
    build:
      context: .
      target: build
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: node ace serve --watch
    depends_on:
      - adonis-mysql

  adonis-mysql:
    image: mysql:latest
    container_name: adonis-mysql
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - ./db:/var/lib/mysql

volumes:
  db:
