services:
  adonis-app:
    image: adonis_app
    container_name: adonis_app
    restart: unless-stopped
    build:
      context: .
      target: build
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    environment:
      - TZ: UTC
      - PORT: 3333
      - HOST: localhost
      - LOG_LEVEL: info
      - APP_KEY: H9XAgbmBG86gDr_DVEUbZLa-UDLU-QzW
      - NODE_ENV: development
      - DB_HOST: 127.0.0.1
      - DB_PORT: 3306
      - DB_USER: root
      - DB_PASSWORD:
      - DB_DATABASE: adonis-mysql
      - SESSION_DRIVER: cookie
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: node ace serve --watch
    depends_on:
      - adonis-mysql

  adonis-mysql:
    image: mysql:7.5
    container_name: adonis-mysql
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - ./db:/var/lib/mysql

volumes:
  db:
